name = "nakaixo"
version = "1.0.0"
licences = ["MIT"]
description = "Our website (written using Nakai) ✨"
repository = { type = "github", user = "nakaixo", repo = "nakaixo.github.io" }

[dependencies]
gleam_erlang = "~> 0.18"
gleam_stdlib = "~> 0.28"
nakai = "~> 0.5"
gleam_community_ansi = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 0.10"
